name: Make Windows

on:
  push:
    branches: [ main ]
    
jobs:
  test:
    runs-on: windows-latest  # 使用 Windows 运行器
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Chrome and ChromeDriver
      run: |
        # 下载 Chrome for Testing
        Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.168/win64/chrome-win64.zip" -OutFile "chrome-win64.zip"
        Expand-Archive -Path "chrome-win64.zip" -DestinationPath .
        $chromePath = "$pwd\chrome-win64\chrome.exe"
        # 将 Chrome 添加到 PATH
        echo "$pwd\chrome-win64" | Out-File -FilePath $env:GITHUB_PATH -Append
        
        # 下载 ChromeDriver
        Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.168/win64/chromedriver-win64.zip" -OutFile "chromedriver-win64.zip"
        Expand-Archive -Path "chromedriver-win64.zip" -DestinationPath .
        echo "$pwd\chromedriver-win64" | Out-File -FilePath $env:GITHUB_PATH -Append
    
    - name: Install dependencies
      run: |
        cd web
        npm install
        cd ..
        cd fantoccini
        cargo fetch
        cd ..
    
    - name: Start chromedriver
      run: |
        Start-Process -FilePath "chromedriver.exe" -ArgumentList "--port=4444" -NoNewWindow -RedirectStandardOutput "chromedriver.log" -PassThru | Select-Object -ExpandProperty Id | Out-File -FilePath "chromedriver.pid"

    - name: Update git submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive
        git submodule foreach --recursive 'git reset --hard origin/main'
        git submodule foreach --recursive 'git clean -fd'

    - name: Copy card directory
      run: |
        xcopy /E /I /Y "card" "web\src\static\card"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Start frontend service
      run: |
        cd web
        npm run build:h5
        cd dist\build\h5
        Start-Process -FilePath "python" -ArgumentList "-m http.server 8000" -NoNewWindow -RedirectStandardOutput "frontend.log" -PassThru | Select-Object -ExpandProperty Id | Out-File -FilePath "..\..\..\frontend.pid"
        # 等待端口可用
        $count = 0
        while (!(Test-NetConnection -ComputerName localhost -Port 8000).TcpTestSucceeded -and $count -lt 30) {
          Start-Sleep -Seconds 1
          $count++
        }
        if ($count -eq 30) { exit 1 }
        cd ..\..\..

    - name: Start cargo
      run: |
        cd fantoccini
        cargo run

    - name: Cleanup processes
      if: always()
      run: |
        # 停止 chromedriver
        if (Test-Path "chromedriver.pid") {
          $pid = Get-Content "chromedriver.pid"
          Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
        }
        # 停止前端服务
        if (Test-Path "frontend.pid") {
          $pid = Get-Content "frontend.pid"
          Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
        }
        # 停止所有 Chrome 进程
        Get-Process -Name "chrome", "chromedriver" -ErrorAction SilentlyContinue | Stop-Process -Force

    - name: Upload pics.zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pictures
        path: .\fantoccini\downloads\