name: Make

on:
  push:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Chrome and ChromeDriver
      run: |
        # 下载 Chrome for Testing
        wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.168/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip
        sudo mv chrome-linux64/chrome /usr/local/bin/google-chrome
        sudo chmod +x /usr/local/bin/google-chrome
        
        # 下载 ChromeDriver
        wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.168/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    
    - name: Install dependencies
      run: |
        cd web
        npm install
        cd ..
        cd fantoccini
        cargo fetch
        cd ..
    
    - name: Start chromedriver
      run: |
        nohup chromedriver --port=4444 > chromedriver.log 2>&1 &
        echo $! > chromedriver.pid

    - name: Update git submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive
        git submodule foreach --recursive 'git reset --hard origin/main'
        git submodule foreach --recursive 'git clean -fd'

    - name: Copy card directory
      run: |
        cp -r ./card ./web/src/static/

    - name: Start frontend service
      run: |
        nohup npm run dev:h5 > frontend.log 2>&1 &
        echo $! > frontend.pid
        sleep 30  # 等待前端服务启动

    - name: Start backend service
      run: |
        nohup cargo run > backend.log 2>&1 &
        echo $! > backend.pid
        sleep 20  # 等待后端服务启动
        ls -la ./fantoccini/
        ls -la ./fantoccini/downloads/

    - name: Upload pics.zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pictures
        path: ./fantoccini/downloads/