name: Make

on:
  push:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Chrome and ChromeDriver
      run: |
        # 1. 安装 Chrome
        sudo apt-get update
        sudo apt-get install -y wget unzip
        sudo apt-get install -y google-chrome-stable
        
        CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f 1)
        echo "Chrome major version: $CHROME_VERSION"
        
        for i in {1..3}; do
          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION") && break
          sleep 5
        done
        
        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
        wget --tries=3 --retry-connrefused "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version
    
    - name: Install dependencies
      run: |
        cd web
        npm install
        cd ..
        cd fantoccini
        cargo fetch
        cd ..
    
    - name: Start chromedriver
      run: |
        nohup chromedriver --port=4444 > chromedriver.log 2>&1 &
        echo $! > chromedriver.pid

    - name: Update git submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach git pull origin main

    - name: Copy card directory
      run: |
        mkdir -p /web/src/static/
        cp -r ~/card /web/src/static/

    - name: Start frontend service
      run: |
        nohup npm run dev:h5 > frontend.log 2>&1 &
        echo $! > frontend.pid
        sleep 30  # 等待前端服务启动

    - name: Start backend service
      run: |
        nohup cargo run > backend.log 2>&1 &
        echo $! > backend.pid
        sleep 10  # 等待后端服务启动

    - name: Archive pictures
      run: |
        mkdir -p fantoccini/downloads  # 确保目录存在
        tar cf - fantoccini/downloads | zip -r pics.zip -
